### ISSUE TITLE
MAIL_SUPPRESS_SEND

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#101]
While setting up a SMTP Server for the new release, i come across something that worth mentioning.

so in ```config.py``` in  ```invenio-app-rdm``` module the ```MAIL_SUPPRESS_SEND``` is set ```True```, and while fetching  a new instance of invenioRDM, in config file ```invenio.cfg``` this env variable ```MAIL_SUPPRESS_SEND``` is not defined so by default its set to ```True```. in order to send mails i needed to set this variable to ```False```.

**Comment by ppanero** [comment]
Hi @mb-wali would it be enough to actually set it in the `invenio.cfg` file? What are provided there are defaults, but in some cases it is more than okay for it to defer.

**Comment by mb-wali** [comment]
Hi @ppanero  yes, setting this value in ```invenio.cfg``` overrides the one in ```config.py```, i also set this value in my ```invenio.cfg``` file to ```False```. 
For other user's it would be good if they are aware that this variable is set to ```True```, because they are not seeing the ```config.py``` file.

**Comment by ppanero** [comment]
Ah okay, sorry I misunderstood your point. I thought there was an error with config loading. I opened an issue in the documentation (https://github.com/inveniosoftware/docs-invenio-rdm/issues/49).

Will try to get a list of those most important configs that are not present in `invenio.cfg`nor `config.py`because they are inherited.

[Closing this issue in favor of the docs one]

Thanks!
