### ISSUE TITLE
FeatureRequest: Multiple roles per creatibutor

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1067]
(transcribing from librarians' feedback at NU)

As part of producing a research output, I want to be able to associate multiple roles with my name, so that all my roles can be reflected,
 
It is more and more common for journals to ask the different roles the author/contributor played in the research output (e.g. PLOS). Right now, InvenioRDM only supports associating one role to one creatibutor. This is in keeping with Datacite, that only associates 1 role per contributor. It is also possible to create multiple creatibutors entries repeating the same name/ids/affiliations but changing the role to reflect that. But it's annoying. This feature is about making that easy.

priority: low

**Comment by lnielsen** [comment]
I agree it might be somewhat annoying to have to repeat contributors. That said often order may be important for each role and I don't see how you easily do that on data model and UX. It's similar to the reasons why we've split creators and contributors into two fields instead of one big. On top of that I think the change will require a lot effort because it  requires changing 1) core data model 2) REST API and 3) Frontend UX + migrating all existing clients.

I'm closing the issue for now as it's unclear how to fix it, and requires a large effort to fix it *if* we find a clear solution.
