### ISSUE TITLE
Record shared by access link remains visible + "editable" in UI even after invalidating the link

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/invenio-app-rdm#1228]
## Steps to Reproduce
Requires two user accounts.
User A: create an editable access link and "share" with User B
User B: use access link, edit the record
User A: destroy the link

User B still sees the record in his "user record" overview with the "Edit" button.
Pressing the button will do nothing in the UI and log a "Permission Error".

## Expected behavior
User B should either not see the Edit possibilities anymore, or not even see the record in his list anymore (its not theirs, User B is just a temporarily invited guest to User A's record, so it should not stay in User B's list permanently)

## Notes
Did not try with just "view" permission and private record, maybe this also should be tested. Especially in that case it would be important for the record to completely disappear from User B once the link is destroyed.

**Comment by max-moser** [comment]
It looks like the issue is that the deletion of the secret link does not trigger a re-indexing of the draft.
The search result (`curl -ks https://localhost/api/user/records\?q\=missing -H "authorization: bearer $TOKEN" | jq .`)  still contains the secret link's ID, which is used by the [permission generator](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/generators.py#L173) to filter search results:
```
        "parent": {
          "communities": {},
          "access": {
            "owned_by": [
              {
                "user": 2
              }
            ],
            "links": [
              {
                "id": "4cf79522-52cc-4e90-aba5-732722971d75"
              }
            ]
          },
          "id": "bkas3-ptb19"
        },
```

However, the record's JSON in the back-end/DB already has the link's ID removed:
```
  "parent": {
    "access": {
      "links": [],
      "owned_by": [
        {
          "user": 2
        }
      ]
    },
    "communities": {},
    "id": "bkas3-ptb19"
  },
```
Thus, an artifact will still show up in user B's dashboard (because the search index isn't up to date), but the permission checks based on the actual record as per DB will fail.
The fix on Invenio's side here is to make sure that the record/draft is re-indexed whenever a secret link is deleted.

As a work-around for now, you could try editing the draft and immediately saving it again (without doing any actual changes), as that will cause the draft/record to be re-indexed, and thus filter out the record/draft from B's dashboard.
