### ISSUE TITLE
Dashboard: UI improvements

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#1245]
Implement the feedback below:

![dashboard_requests](https://user-images.githubusercontent.com/2089455/153627375-3ad787aa-9d81-4ea4-bbbb-49ef2ab7deb9.png)

**Comment by lnielsen** [comment]
The dashboard should be style similar to communities:

![Screenshot 2022-03-01 at 00 47 56](https://user-images.githubusercontent.com/1698163/156078010-01ba84c9-d76a-4a77-a5bd-9cd8c316cc09.png)

Changes as far as I can see:

- Header:
  - Replace user with "My dashboard" (just for the release, so simply comment the code, don't delete it, afterwards we change it back).
  - Smaller placeholder picture
  - Light grey background (same colour as communities.
-  Tab
  - Align with communities style - e.g. remove the outer box  
  - Check alignment, so that sides are properly aligned.
