### ISSUE TITLE
I18N: EXTRACT, PUSH & PULL

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#1664]
## extract & push
```bash
# python
pip install -e ".[all,postgresql,elasticsearch7,tests]"
python setup.py extract_messages
tx push -s

# js
npm run extract_messages
```
- [x] [react-invenio-deposit](https://github.com/inveniosoftware/react-invenio-deposit)
- [x] [invenio-i18n](https://github.com/inveniosoftware/invenio-i18n)
- [x] [invenio-app-rdm](https://github.com/inveniosoftware/invenio-app-rdm)
- [x] [invenio-access](https://github.com/inveniosoftware/invenio-access)
- [x] [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts)
- [x] [invenio-communities](https://github.com/inveniosoftware/invenio-communities)
- [x] [invenio-drafts-resources](https://github.com/inveniosoftware/invenio-drafts-resources)
- [x] [invenio-formatter](https://github.com/inveniosoftware/invenio-formatter)
- [ ] [invenio-files-rest](https://github.com/inveniosoftware/invenio-files-rest)
- [x] [invenio-oaiserver](https://github.com/inveniosoftware/invenio-oaiserver)
- [x] [invenio-oauth2server](https://github.com/inveniosoftware/invenio-oauth2server)
- [ ] [invenio-oauthclient](https://github.com/inveniosoftware/invenio-oauthclient)
- [x] [invenio-pidstore](https://github.com/inveniosoftware/invenio-pidstore)
- [x] [invenio-rdm-records](https://github.com/inveniosoftware/invenio-rdm-records)
- [x] [invenio-records](https://github.com/inveniosoftware/invenio-records)
- [x] [invenio-records-permissions](https://github.com/inveniosoftware/invenio-records-permissions)
- [x] [invenio-records-resources](https://github.com/inveniosoftware/invenio-records-resources)
- [x] [invenio-saml](https://github.com/inveniosoftware/invenio-saml)
- [x] [invenio-search-ui](https://github.com/inveniosoftware/invenio-search-ui)
- [x] [invenio-theme](https://github.com/inveniosoftware/invenio-theme)
- [ ] [invenio-userprofiles](https://github.com/inveniosoftware/invenio-userprofiles)
- [x] [invenio-vocabularies](https://github.com/inveniosoftware/invenio-vocabularies)
- [x] [marshmallow-utils](https://github.com/inveniosoftware/marshmallow-utils)
- [x] [invenio-requests](https://github.com/inveniosoftware/invenio-requests)
- [x] [invenio-users-resources](https://github.com/inveniosoftware/invenio-users-resources)
- [x] [invenio-previewer](https://github.com/inveniosoftware/invenio-previewer)
- [x] [invenio-administration](https://github.com/inveniosoftware/invenio-administration)

## pull
**python**
`tx pull -l de -f`

**js**
```bash
tx pull -l de -f
npm run compile_catalog lang de
```
- [x] pull translations for the above modules and create/merge PR.

## release
- [ ] make new releases of the above modules.

**Comment by chriz-uniba** [comment]
From this list I identified the following transifex packages to translate:

- [ ] react-invenio-deposit
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/react-invenio-deposit-messages

- [ ] invenio-i18n
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-i18n-messages


- [ ] invenio-app-rdm
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-app-rdm-messages


- [ ] invenio-app-rdm-ui
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-app-rdm-messages-ui


- [ ] invenio-access
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-access-messages

- [ ] invenio-accounts
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-accounts-messages


- [ ] invenio-communities
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-communities-messages


- [ ] invenio-communities-ui
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-communities-messages-ui


- [ ] invenio-drafts-resources
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio_drafts_resources-messages

- [ ] invenio-formatter
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-formatter-messages


- [ ] invenio-files-rest
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-files-rest-messages

- [ ] invenio-oaiserver
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-oaiserver-messages

- [ ] invenio-oauth2server
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-oauth2server-messages

- [ ] invenio-oauthclient
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-oauthclient-messages

- [ ] invenio-pidstore
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-pidstore-messages

- [ ] invenio-rdm-records
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-rdm-records-messages

- [ ] invenio-records
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-records-messages

- [ ] invenio-records-permissions
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-records-permissions-messages

- [ ] invenio-records-resources
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio_records_resources-messages

- [ ] invenio-saml
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-saml-messages

- [ ] invenio-search-ui
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-search-ui-messages

- [ ] invenio-search-ui-js
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-search-ui-messages-js

- [ ] invenio-theme
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-theme-messages

- [ ] invenio-userprofiles
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-userprofiles-messages

- [ ] invenio-vocabularies
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-vocabularies-messages

- [ ] marshmallow-utils
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/marshmallow-utils-messages

- [ ] invenio-requests
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-requests-messages

- [ ] invenio-requests-ui
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-requests-messages-ui

- [ ] invenio-users-resources
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-users-resources-messages



Notes:
- Some packages are using `_` instead of `-` in transifex, e.g.
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio_records_resources-messages
  - https://www.transifex.com/inveniosoftware/invenio/translate/#de/invenio-users-resources-messages
- For some packages there are additional `ui` and `js` -packages in transifex.
  -  The list stated by @mb-wali contains 25 packages, due to the additional `ui` and `js` packages in transifex our list has some more packages to translate.
  - Site note: It would be great to only have the needed packages available in transifex.

**Comment by chriz-uniba** [comment]
Update:
- We translated and reviewed all above mentioned packages in transifex (I hope we didn't oversee one) in a first "draft".
- I reviewed this: https://github.com/inveniosoftware/invenio-rdm-records/pull/889#pullrequestreview-993403018
- Is this package used "invenio-previewer-messages" - it was not part of the packages that we were asked to translate?
- It would be great, if we could remove all unused packages in transifex (that would make working and searching across packages in transifex so much easier).
- We found several flaws and bugs related to translations, which we will report and hopefully fix as a next step.

- Next steps: bringing translations back to the packages. Taking a look at the current status in a real invenio instance. Fix bugs (programmatically bugs, english sentences bugs, ...) , list still existing translation issues, go through a second round of translation.

**Comment by chriz-uniba** [comment]
By the way: Are there any other vocabularies, that still need translations? (Record-types or so?)

**Comment by chriz-uniba** [comment]
@mb-wali what about the following:
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- maybe? https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/languages.yaml
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml

- maybe check the rest of this folder: https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/fixtures/data/vocabularies

**Comment by mb-wali** [comment]
> @mb-wali what about the following:
> 
> * https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
> * https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
> * maybe? https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/languages.yaml
> * https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
> * https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
> * https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
> * maybe check the rest of this folder: https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/fixtures/data/vocabularies

They should be translated, but does not require transifex - simply adding a new row for `de` is enough e.g:
```yml
  title:
    en: Publication
    de: German version
```
I don't think we could integrate these on this release - but if you (german team) finish translating we could merge them for next release.
