### ISSUE TITLE
Landing page: tablet/mobile view for files table

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-app-rdm#1735]
![files-mobile-desktop](https://user-images.githubusercontent.com/21052053/173547266-f6a39f26-72c1-4325-80e8-55145a396577.png)

**Comment by alejandromumo** [comment]
Context on why this issue happened:
- On mobile, the responsive table for community members had the following  behaviors:
  -  table data elements from the same row are stacked vertically
  -  table headers are removed, if the class `selected-member` is specified.
  -  cell without data-label (first column) has a gray background to divide table rows, if the class `selected-member` is specified.
  -  data-labels are aligned with each table data. 
- Styling rules were being applied to every table, including files list, even though some rules were specific for communities tables (e.g.  required the class `selected-member` to work properly).

Solution:
- The class `selected-member` was removed, as we felt that its semantic meaning was low and it was very spefic for members table.
- On a responsive table, a `responsive-main-cell` can be specified that will have a gray background on mobile. It will work as a "divider" between table rows stacked vertically on mobile.

Invitations table was fixed by this change. 

Note: initially a class was created for `responsive` tables, so this styling would not be applied to other tables. But after discussing with @jennur, it made sense to me that every table should be responsive by default. I did not find any table that is breaking due to this styling, in fact invitations table was fixed, but it might be wise to be double checked by reviewers

Note: we noticed that files table under the upload page is missing. a data-label. I will open a new issue and fix it  there, to avoid working on many bugs on the same issue.

**Comment by alejandromumo** [comment]
Results

Files list: 

![Screenshot at Jun 17 10-21-20](https://user-images.githubusercontent.com/21204744/174258105-f806147a-03a2-4772-afcf-58bf3e25bc5a.png)

Invitations table was also fixed:

![Screenshot at Jun 17 10-23-45](https://user-images.githubusercontent.com/21204744/174258514-0e49dc8a-7306-4cc1-8e71-98309087cc23.png)
