### ISSUE TITLE
export: DataciteJson and DataciteXml fails to export if record has awards

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1904]
## Describe the bug
Exporting of record with `Awards` causes internal error.

## Steps to Reproduce
1. Go to 'New upload'
2. Fill in required fields
3. Add an award
4. Publish the record
5. Export record in Datacite Json or Datacite Xml format
6. See error

## Expected behavior
Record should be correctly exported.

**Comment by ppanero** [comment]
Notes from a quick check:
- It does not have to do with CF, like it fails even if the record has no CFs.
- Doing some tests it only happens with some funders
- It is a DB issue (not ES as we thought)
- The command to import them is sync, and fails initially because fixtures are async (chicken egg)
- Im not sure how to solve it now... needs debugging. But is seems to come from the creation of awards (not the datacite export). 
- We need to backport fix to v9 since it will also fail there
