### ISSUE TITLE
404 error on records result page if vocabularies are missing

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1952]
Package version (if known): [v11.0.0.dev2](https://github.com/inveniosoftware/invenio-app-rdm/commit/f058604ae3ee1c3f243cd5cee3e85057169f889c)

## Describe the bug
If vocabularies are missing, when doing a search for records it should display an internal server error (code 500), but instead a 404 is displayed without information about what went wrong.

## Steps to Reproduce
1. Setup an instance without running the `invenio-cli services setup`
2. Start the containers
3. Initialise the database and indexes
4. Access the records search page and see 404

## Expected behavior
A 500 internal error should be raised instead of a 404

**Comment by ppanero** [comment]
In invenio-vocabularies we have `read`, `read_all` and `read_many`. When searching for generic vocabularies, we give two parameters vocabulary `type` and `ids` (e.g. _resourcetype_ and _publication_). In the case that publication does not exist the result would be:
- `read` --> `NoResultFound` (404) 
- `read_many` and `read_all` --> empty search result (i.e. `hits: []`)

However, all three methods assume that the vocabulary type (e.g. _resourcetype_) exists in db (we are querying `.one()` with no try/except). Then, it make the search page with a 404 because a `NoResultFound` is risen. It leads me to:
- `read` --> `NoResultFound` (404) . This is still correct, however, should we expose in the error if what does exist is the type instead of the actual id?
- `read_many` and `read_all` --> **Here is the important part**:
    - Imitating the empty search result (i.e. `hits: []`) would be the desired output for internal usage (e.g. facets). However, it is semantically incorrect, since it's not empty but rather doesn't exist.
    - 404, would need to handle this internally when labelling vocabularies <-- I'm leaning towards this solution.
