### ISSUE TITLE
sort by: most viewed

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2143]
- [ ] hook up the  usage statistics to search sorting, similarly to current state on zenodo:
![image](https://user-images.githubusercontent.com/38131488/224329581-2115919a-2de8-45d3-98a1-953c549b85dd.png)
- [ ] display usage statistics on the search items as shown on the mockup:
<img width="2193" alt="Screenshot 2023-03-10 at 14 39 14" src="https://user-images.githubusercontent.com/38131488/224330478-0650c87b-a968-498c-9bac-8e126077d502.png">

**Comment by max-moser** [comment]
A bit of discussion regarding this happened in [Discord](https://discord.com/channels/692989811736182844/1073182429365424178/1079792482507829389).
My findings:

so i just did a bit of digging to check how the search works under the hood and how easy or hard it would be to implement a sorting by anything that's not indexed in the SE (search engine)
on the search pages, the top-right "Sort by" drop-down determines the value for the `sort` arg in the `/api/records?sort=<sort-by-value>` call that's performed to the REST API
there, it's the `resource` who handles the API call, and here the `request_search_args` parses the search-related request args (via a schema for type checking and validation, etc.) and puts them into the `resource_requestctx` that's passed as params to `service.search()`: https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/records/resource.py#L80
this then goes through a bunch of service methods to figure out which parameters should be applied to the search and construct an appropriate SE query, which will then be executed and turned into a `result_list`: https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/records/service.py#L225 
so i wonder, can we even ever fully support a true "sort by views" if the stats aren't indexed in the SE?
because given there's enough records in the search results of that query to not yield all records in one single go, we will always be limited to the records that are in the current result page
if the record with the most views is (for whatever reason) not contained in the search result page, we can't really add it
