### ISSUE TITLE
Inconsistent NewVersion button behavior on some records

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-app-rdm#2197]
Package version (if known): 12 beta

## Describe the bug
On some records, when you click on edit and then new version, you end up in a state where you can't keep going, the GIF video will explain it:

![test-version-on-second-community](https://user-images.githubusercontent.com/36583694/232743970-2ddb1f8e-836f-4644-9c3c-136ac1b2d0a0.gif)

## Steps to Reproduce
1. Go to ['record'](https://inveniordm.web.cern.ch/records/vnj6t-fv530)
2. Click on 'edit'
3. Click on 'create new version'
4. See that nothing happen

## Expected behavior
See the import file button, and I am able to edit files.

## Additional context
It's hard to replicate it on each record, and I can't find what is causing the problem, I created another record from scratch and it works as expected.

**Comment by tmorrell** [comment]
We've seen this behavior sporadically in our v9 production instance. It's also intermittent-you can sometimes come back to a record where "new version" didn't work after a few hours and it will work again. I haven't found any pattern to when it happens.

**Comment by tmorrell** [comment]
This came up again, and I got farther in debugging. My solution above doesn't work universally.

What I observed today was a record where 'next_draft_id' got set to the identifier of the record. 

```Output of record.versions: VersionsManager (parent_id: c1e422cb-dff8-47eb-9482-3fc9f9b5d86c, index: 1, latest_id: 882c7be5-9826-4bb4-b4be-53dfc13eaa25, latest_index: 1, next_draft_id: 882c7be5-9826-4bb4-b4be-53dfc13eaa25)```

This resulted in the `new_version` function call not working, since it just returned the parent record https://github.com/inveniosoftware/invenio-drafts-resources/blob/02c33f144e0b1fbf6796a5c1671397a39fdb0208/invenio_drafts_resources/services/records/service.py#L370

I was able to clear this with the following script:

```
record = service.record_cls.pid.resolve(pid)
    print(record.versions)
    record.versions.clear_next()
    record.commit()
    db.session.commit()
    service.indexer.index(record)
```

Is there a scenario where latest_id and next_draft_id should be the same? Maybe if there is an additional check that next_draft_id and last_id are different added at https://github.com/inveniosoftware/invenio-drafts-resources/blob/02c33f144e0b1fbf6796a5c1671397a39fdb0208/invenio_drafts_resources/services/records/service.py#L370  the problem would be solved?

I'm still not sure how next_draft_id ended up getting set in the first place.

**Comment by fenekku** [comment]
We had this sitting in our backlog and it's causing issues to our users, so I might as well give it a shot.

**Comment by zguillen** [comment]
Hello all:
I have some bummer news to add to this issue. We are seeing this same issue on our prod instance of RDM. I applied the fix from the referenced PR to our v9.1 RDM instance and it did not change this behavior for us. I simply copied the one line “if not record.is_published:” over and didn’t merge the PR or anything.  

Another larger bummer is that not only do we get this behavior originally reported but an error in the UI as well for this case:
1.	Click Edit on a published record
2.	Click New version (UI renders edit draft of published instead of new version draft)
3.	Click discard changes.
4.	Go back to published record’s landing page and click new version 

UI will now show this error message:
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/1569461/378c7af8-413b-420f-bbe6-cb26bd2f9376)

Exception printed in the log is, “sqlalchemy.exc.NoResultFound: No row was found when one was required” triggered from this line “next_draft = self.draft_cls.get_record(” of invenio_drafts_resources/services/records/service.py new_version.

Once a record gets into this state the only way I’ve been able to recover from it is to run the script  @tmorrell  posted above (a BIG thank you!) https://github.com/inveniosoftware/invenio-app-rdm/issues/2197#issuecomment-1527888618 

Is there any advice you have for me on this? I’m pretty stumped still ☹

**Comment by zguillen** [comment]
Yay, @zzacharo! this PR is fixing the bug for me now.  I don't know what was going on when I applied the fix originally but still seeing the error...I must have been testing with records already in a bad state?  

My steps to reproduce the incorrect behavior and error were:
1. create and publish a record
2. **important** wait an hour to be sure the cleanup_drafts ran
3. click edit button on the published record
4. go back and click the new version button
5. --->this is where the UI will show the edit draft page instead of new version draft
6.  click the discard draft button
7. --->this is where the UI will render the not found error

after applying the fix from this PR I no longer get the behavior in step 5 nor the error in step 7.  Thank you so much!

**Comment by zzacharo** [comment]
Hey @zguillen ! That's great! Most likely it was because, as you said, you were testing your fix in already broken records but having also the fix from the https://github.com/inveniosoftware/invenio-drafts-resources/pull/244 will double save any indexing problem you might experience if you change the interval of the `cleanup_drafts` task!
