### ISSUE TITLE
featured community: description displays HTML tags

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#2216]
Package version (if known): latest

## Describe the bug
A community with html tags in its description is not properly displayed when featured.

## Expected behavior
Display the text without the html tags or properly render the html.

## Screenshots (if applicable)
![Screenshot 2023-05-12 at 14 49 17](https://github.com/inveniosoftware/invenio-app-rdm/assets/22594783/2838284f-ee06-43c4-b985-af2f0ca0ab4b)

## Additional context

Found https://zenodo-rdm-qa.web.cern.ch/communities

**Comment by slint** [comment]
Actually, this is an issue with the `description` field in general in data migration... In legacy Zenodo, `description` was a rich field, but now it's [just plain text](https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/communities/schema.py#L114). If we convert the field to rich text, that's fine with me, but that requires also changes in the creation/update settings forms.

**Comment by jennur** [comment]
> Actually, this is an issue with the `description` field in general in data migration... In legacy Zenodo, `description` was a rich field, but now it's [just plain text](https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/communities/schema.py#L114). If we convert the field to rich text, that's fine with me, but that requires also changes in the creation/update settings forms.

@slint I think there are some misunderstandings regarding this task. My understanding is that this was reported as a bug in the frontend, but I think the issue is that these descriptions were added _before_ the field change from rich text to plain text? Thus I believe this issue can be fixed through the community settings in the UI. If this is the case, I think this task and my PR can be ignored and closed.

**Comment by slint** [comment]
> **If this is the case, I think this task and my PR can be ignored and closed.**
> 
> (I believe the reason for the change from rich text to plain text was because we added the new about page, and that this `description` field is now only intended for a sentence or two to show e.g. on the cards etc.)

Correct, this is a data migration issue, and not a UX issue, sorry for all the trouble 😬. 

So the way to solve this is that we migrate both the legacy `description` and about page field to the `page`. That means `description` remains empty.

**Comment by ntarocco** [comment]
I am not sure that I understand very well the final outcome. I think that it makes sense to have the description field as HTML. Do you want to keep it plain text instead?

**Comment by jennur** [comment]
> I am not sure that I understand very well the final outcome. I think that it makes sense to have the description field as HTML. Do you want to keep it plain text instead?

I don't think it makes sense that it is an HTML field, as it is supposed to be a short (and truncated) description for the cards etc.

**Comment by slint** [comment]
Ok, a final decision for this one (@ntarocco and @lnielsen, feel free to +1 or comment):

- We shorten the `description` field to 250 chars (as described in https://github.com/inveniosoftware/invenio-communities/issues/402)
    - the reasoning is that this is meant to be a short tagline on card-list displays and search results.
    - we don't want rich text because it's a pain to render links/bullet-lists in these card views
- We don't do any data migration recipe for this. If an instance has communities with descriptions longer than 250 chars, they'll just have trouble when updating community settings (since the new validation rule will kick in). At that point, they'll have to make a decision on where to move the extra content.

---

For the Zenodo data migration (to be shelved/moved to `zenodo/zenodo-rdm`) this has the following consequences:

- If a `description` fits in 250 chars and does not contain any styling or special markup (i.e. bold, italics, links, bullet-lists), we strip HTML tags, and populate the `description` field.
- If it doesn't, we join/pre-pend it with the `page` field to avoid data loss.
