### ISSUE TITLE
Make UI URLs configurable

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#232]
**NOTE**: This task has been much clarified over time so its definition has been rewritten to make it evident what it's about now

Make invenio-app-rdm UI URLs configurable via config.py variables. This then means percolating that knowledge across the codebase/modules using these same config variables.

- [x] in invenio-app-rdm
- [x] in invenio-records-resources
- [x] in react-invenio-deposit

We can use a callable blueprint. This way a ResourceConfig can be defined in the config.py and fetched with an application context because the application is created at time of blueprint registration.

The default URL values should be:

-    /uploads - List user records
-    /uploads/new - Create a new record (prior to having an ID, as soon as we have an ID by pressing save, the React app rewrites the URL to the one below).
-    /uploads/:id - Editable (draft) records
-    /search - Main search result page.
-    /records/:id - A published record

**Comment by lnielsen** [comment]
This is only for the UI right?

1) For the defaults I would go with:

- ``/uploads`` - List user records
- ``/uploads/new`` - Create a new record (prior to having an ID, as soon as we have an ID by pressing save, the React app rewrites the URL to the one below).
- ``/uploads/:id`` - List user records
- ``/search`` - Main search result page.
- ``/records/:id`` - A published record

2) We should not in my opinion match up the REST API URLs. These URLs communicate structure for an end-user on where you are on the site, hence (e.g. ``/uploads`` matches up with the "Uploads" button). That said, not many browsers actually 
show the full URL anymore.

3) Yes, we would have to be able to customize them, to e.g. maintain previous URLs from a legacy system. (e.g. Zenodo uses ``/record`` (singular). Changing it would require updating 1M+ DOIs.

3) Can we use Invenio-Records-UI for most of it via custom view functions instead of building new views and new dynamic blueprint creation?

**Comment by fenekku** [comment]
0) The problem around allowing instances to configure URLs **does** rear its head also for the API, but this specific comment was indeed about the UI. I made an issue for the API case last week: https://github.com/inveniosoftware/invenio-records-resources/issues/67

1 - 2) :heavy_check_mark: Will go for the URLs in 1).

3) Ok so we can't cut the Gordian knot of the problem. Got it.

4) The issue with invenio-records-ui is this: https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/views.py#L117 . No matter the custom view implementation we pass, resolution is still handled with the asdsumption that there is a PID to resolve (which is not the case for the URL of the upload page). Perhaps it is simplest to change that to allow for non-resolution needing URLs (looking at the needed changes it looks medium sized (~2 days), but maybe there are gotchas I don't know). It does seem like we can pass the `record_class` and so get a little more control over resolution than I initially thought.

**Comment by fenekku** [comment]
**Solution**
- I think providing a callable blueprint is actually the way to go, this way a `ResourceConfig` can be defined in the config.py and fetched with an application context because the application is created at time of blueprint registration.
