### ISSUE TITLE
Locking version when executing "invenio-cli init rdm"

### ISSUE THREAD

**Issue by treecon** [inveniosoftware/invenio-app-rdm#2377]
When executing command `invenio-cli init rdm -c v11.0`, the client downloads the latest commit on branch v11.0 from repository:
https://github.com/inveniosoftware/cookiecutter-invenio-rdm

Hence an installation with the same version, may not be same with an installation of the same version deployed some time ago.

This can be an issue when multiple people from our team work at the same project (having different repo versions). Is there a way to select a specific commit when executing the `init rdm` command?

Thanks!

**Comment by fenekku** [comment]
:wave: @treecon ! The `-c` or `--checkout` option does allow you to specify a commit when initializing your project. Nevertheless, your team shouldn't need to do that if you all work on the same project.

When multiple developers are working on the same project, one developer goes through the local installation steps and runs `invenio-cli init rdm -c v11.0`. After that step, they commit the code and push it to the common repo for the team. Then other team members checkout that code and continue on the local install steps after the `init` step (that would be the `invenio-cli install` step). From then on, everyone on the team should have the same codebase. There may be a need to share some sensitive files among team members along the way but that's left up to the developers how to deal with it.

Also, we typically don't change the content of a cookiecutter branch with a version name, so those are pretty stable. In this case, `v11.0` was changed in June because we were giving a yearly tutorial at a conference and needed to make these changes for the session in very short time frame. Nevertheless, those shouldn't be too problematic (and no changes since then occurred). 

For any other question, we suggest using: https://discord.com/invite/8qatqBC to get faster turnarounds. Friendly people will be happy to help. I'll close this for now (feel free to reopen to finish this conversation if more questions, but use the discord for new queries).
