### ISSUE TITLE
domains: creating new domain fails if flagged is not set

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#2641]
Package version (if known): v12.0.0b3.x

## Describe the bug
When creating a domain via the administration panel, the "Flagged" checkbox must be clicked otherwise it leads to validation error.

## Expected behavior

The checkbox is not required, thus it should be able to omit ticking it. Moreover, the required properties seem to be more than the "Domain" input. This needs to be verified and adapt the UI accordingly e.g add red asterisks to the corresponding fields.

## Screenshots (if applicable)
![Screenshot 2024-04-05 at 14 55 02](https://github.com/inveniosoftware/invenio-app-rdm/assets/22594783/a9e663dd-e1a9-44e7-bf00-c4073848459d)

**Comment by utnapischtim** [comment]
short notice:
following lines: https://github.com/inveniosoftware/invenio-administration/blob/main/invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js#L29-L34  have to be backported ontop of v2.2.3 of invenio-administration

ontop of v2.2.3 is necessary because v2.3.0 increases the dependency to `invenio-records-resources` and therefore introduces a version conflict with the uses `invenio-rdm-records` version in `invenio-app-rdm`

**Comment by utnapischtim** [comment]
fixed by https://github.com/inveniosoftware/invenio-administration/releases/tag/v2.2.4
