### ISSUE TITLE
Page specific header template (jinja)

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#410]
Per @zzacharo ' comment, it might be interesting to be able to change the jinja template header on a per-page basis with config variables. Each page where it makes sense to provide this level of customization would have 

```jinja2
{% block page_header %}
{% include config.<PAGE>_HEADER_TEMPLATE or config.THEME_HEADER_TEMPLATE %}
{% endblock page_header %}
```

Note that this is sugar. Each page's template can already be overridden. So an installer could place the header they want in their overridden page like so:

```jinja2
{% extends config.<PAGE>_TEMPLATE %}

{% block page_header %}
{% include <PAGE HEADER_TEMPLATE> %}
{% endblock %}
```

**Comment by zzacharo** [comment]
I think what's most important, is to ensure that the templates are designed so they provide meaningful blocks e.g `page_header` so users can minimize the amount of code they need to change in order to customize specific parts. I think we can close this one and maybe open specific issues per use case! @fenekku feel free to reopen it if you think otherwise :)

**Comment by fenekku** [comment]
I was perfectly happy with the way things were, so I am not re-opening this :smirk_cat:
