### ISSUE TITLE
deposit form: description text editor allows tables, but it should not be allowed and landing pages strips them out

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#596]
The deposit form description field text editor should only allow to add the html tags which are actually allowed.
See list of allowed tags here: https://github.com/inveniosoftware/marshmallow-utils/blob/master/marshmallow_utils/fields/sanitizedhtml.py#L15-L42

Expected:

Only valid tags are saved. Only valid tags are rendered. (right now invalid tags are saved).

**Comment by zguillen** [comment]
We're on an older version of RDM that still allows tables in the description field. A user tried adding one and noticed that the table wasn't being rendered correctly on the landing page (the issue this issue is about). However, instead of removing the table from the descriptions config we'd like to fix the landing page to properly render them. Is there a reason why RDM's solution to this issue was to remove support for tables? Just wondering if there's a problem with allowing tables on the landing page before I tackle this task :)
