### ISSUE TITLE
`revision_id` jumps with two when publishing a new record

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#647]
Package version (if known): 1.0.0

## Describe the bug
When a record is published the revision_id is increased each time by 2.  Investigate why this is happening and understand if there is a bug in the publish flow.

## Expected behavior

The `revision_id` should be incremented by 1!

**Comment by fenekku** [comment]
- [x] database isolation level understanding 
- [x] version level counter understanding
- [ ] how/when we change the `revision_id` in our code

**Comment by fenekku** [comment]
Summary of investigation

One of the `RDMRecordServiceConfig`.components causes the `revision_id` to increment one more time than otherwise.
Its components are:

```python
components = [
    MetadataComponent,
    AccessComponent,
    DraftFilesComponent,
    PIDComponent,
    VersionSupportComponent,
]
```

VS

components from `RecordDraftServiceConfig`

```python
components = [
    DraftMetadataComponent,
    PIDComponent,
]
```

`DraftFilesComponent` does

```python
  record.bucket = bucket
  record.bucket_id = bucket.id  
```

which `invenio-rdm-records/tests/resources/test_resources.py::test_create_publish_new_revision`
warns is causing multiple revision bumps. I am taking it at its word :shrug: .

The service tests service tests in `invenio-drafts-resources/tests/services/test_record_service.py::test_publish_draft`has its `revision_id == 1` which is consistent with the identified scoping/source.

Does that make sense? Was it intentional?
