### ISSUE TITLE
Prevent creation of new version if all metadata + files the same

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#843]
## Is your feature request related to a problem? Please describe.
As a depositor, I may inadvertently create a new version with the same file and then to correct my mistake I need to create yet another version.

There is no prevention from creating a redundant new version right now. Whether we just consider files or files + metadata when assessing "sameness of version" is up for grabs. Zenodo does only file I believe. 

## Describe the solution you'd like
A UI error/warning like our other ui warnings, indicating that the record is the same.

**Comment by lnielsen** [comment]
I think this is likely to be highly instance dependent what is expected and what should be prevented. Today you actively have to import files from a previous version and we edit out the publication date so that you must change some minimal metadata in order for a publishing to finish. Also, it's not clear what to do if you accidentally a version - e.g. in some cases I think the right thing would be to request a inactivation of the version.

![Screenshot 2022-02-09 at 11 25 33](https://user-images.githubusercontent.com/1698163/153179223-839aca20-228e-493b-8cf1-623d3f093c1e.png)
