### ISSUE TITLE
landing page: UX review and styling

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#988]

**Comment by jennur** [comment]
**Change suggestions for the landing page:** 

### Generally
* Be consistent with the use of headlines and spacing to create a clear hierarchy.
* Font weight (300) is very thin and hard to read, could be 400
* Bug?: Font (Lato) is not loading unless it's installed in the local system

### Side bar
* Move the keywords, DOI, license, upload information, etc. to the side bar as this is key information about the record and should be easy to find.
#### Export
* Change the export selection to dropdown, rather than blue links and download the exported file directly.

### Contributors
* Group all the contributor-types, and display the groups horizontally instead of vertically to avoid too much whitespace, and to make it easier to go through the related content without scrolling and losing context.
* Have only one "show affiliations"-button if they're all showing the same content (it's not necessary to have more than one button for the same thing).
* Move "show-affiliations"-button to the very right, bottom of the section to indicate that the extra content is relevant for all the groups, and that it will show up below.

### Citation
* Change the citation style selection to a dropdown. I found myself hesitating to click the blue links (I was wondering if they would take me somewhere)
* Follow the pattern of having the interactive elements all the way to the left if they are interactive with all the content of the section.

### Description
* Additional descriptions are pulled out from the details section and displayed as subsections of the main description.

### Files
* Remove the preview button from the file-list. It doesn't seem like it is doing anything? And the preview is already open and easily accessible right above. Instead add a comment rather than a button (e.g. "In preview") to show that this is the file being previewed.

### Details section
* Reorganise the details-content in the main section to increase the readability. Stacking the text vertically instead of horizontally (especially when there are multiple levels) makes it easier to read and understand. A vertical listing makes sure that the reader don't have to move the eyes around too much to see the related content.

<img width="1296" alt="Screenshot 2021-07-28 at 09 31 11" src="https://user-images.githubusercontent.com/21052053/127289155-1a26c1bb-ae1d-40be-895e-abd6d79e8331.png">
<img width="1296" alt="Screenshot 2021-07-28 at 09 31 26" src="https://user-images.githubusercontent.com/21052053/127289287-8fc023e4-f24f-4ad8-b5cc-fdc7701702d9.png">
<img width="1297" alt="Screenshot 2021-07-28 at 09 31 43" src="https://user-images.githubusercontent.com/21052053/127289190-761ebdf3-fe53-4853-befb-d345be7bbd8b.png">

**Comment by lnielsen** [comment]
Fixed
