### ISSUE TITLE
test: perform a DOI registration test with all form fields filled out 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#995]

**Comment by tmorrell** [comment]
I've tested this, and all the metadata goes through to DataCite. Only issues I noticed were https://github.com/inveniosoftware/invenio-rdm-records/issues/775 and that the API url is used instead of the landing page. That should be resolved by https://github.com/inveniosoftware/invenio-rdm-records/pull/566 or changing the value at https://github.com/inveniosoftware/invenio-rdm-records/blob/0dd506b6b899d12c7b4c5297e5e2cf9231da2999/invenio_rdm_records/services/pids/providers/datacite.py#L145
